services:
  - type: web
    name: go-game
    runtime: go
    buildCommand: apt-get install -y gnugo && go build -o server .
    startCommand: ./server
    envVars:
      - key: PORT
        value: 8080
